development:
  adapter: postgresql
  encoding: unicode
  database: parkfind
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: parkfind_test
  pool: 5
  host: localhost